### ISSUE TITLE
Graph lines not being displayed

### ISSUE THREAD

**Issue by kaizersoje** [mawinkler/astroweather-card#13]
I have noticed since upgrading to v0.31.0 and after, the graph is not being displayed.

```yaml
type: custom:astroweather-card
entity: weather.astroweather_home
details: true
current: true
deepskydetails: true
forecast: true
graph: true
number_of_forecasts: '5'
line_color_condition: '#f07178'
line_color_condition_night: '#eeffff'
line_color_cloudless: '#c3e88d'
line_color_seeing: '#ffcb6b'
line_color_transparency: '#82aaff'
```

![image](https://github.com/mawinkler/astroweather-card/assets/54566217/3f9500cc-c7d9-4c72-9388-3701d553d08f)

Also, just a suggestion - it would be good to have  the card version added to the browser console just like some of the other cards in HACS.

![image](https://github.com/mawinkler/astroweather-card/assets/54566217/9571ec35-6a5b-409e-a97b-2fb532900aac)
